# Change these first
owner: GreathostRo # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository

sites:
  - name: Server Ultra
    url: https://ultra.greathost.ro
  - name: Server Gaming
    url: https://game.greathost.ro

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.greathost.ro
  # baseUrl: /Uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Status - Greathost.ro
  introTitle: "Monitorizare stare servere Greathost.ro"
  introMessage: Vizualizați starea serverelor Greathost.ro în timp real, toate lucrările de mentenanță sau problemele apărute vor fi afișate aici.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
